config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :wagons
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
    @count_of_buisness = Wagon.where(train_id: params[:id]).where(comfort: 'Buisness').count
    @count_of_econom = Wagon.where(train_id: params[:id]).where(comfort: 'Econom').count
    @bottom_seats = Wagon.where(train_id: params[:id]).sum(:bottom_seats)
    @top_seats = Wagon.where(train_id: params[:id]).sum(:top_seats)
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_for(train) do |f| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :current_station %>
    <%= f.select :current_station_id, RailwayStation.all.collect {|p| [ p.title, p.id ] } %>
  </div>

  <div class="field">
    <%= f.label :route %>
    <%= f.select :route_id, Route.all.collect {|p| [ p.title, p.id ] } %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= train.current_station_id %></td>
  <td><%= train.route_id %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <%= render train %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <div class="field">
  <strong>Number:</strong>
  <%= @train.number %>
  </div>

  <div class="field">
  <strong>Cureren Station:</strong>
  <% if @train.current_station.present?%>
    <%= @train.current_station.title %>
  <% else %>
    Not on Station
  <% end %>
</div>


  <div class="field">
  <strong>Route:</strong>
  <% if @train.route.present?%>
    <%= @train.route.title %>
  <% else %>
    No route
  <% end %>
  </div>

  <div class="field">
  <strong>Buisness class wagons:</strong>
    <%= @count_of_buisness %>
  <strong>Econom class wagons:</strong>
    <%= @count_of_econom %>
  <strong>Count of bottom seats:</strong>
    <%= @bottom_seats %>
  <strong>Count of top seats:</strong>
    <%= @top_seats %>
  </div>


</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>