config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wagon.rb
class Wagon < ApplicationRecord
  belongs_to :train
end

app/controllers/wagons_controller.rb
class WagonsController < ApplicationController
  before_action :set_wagon, only: [:show, :edit, :update, :destroy]

  # GET /wagons
  # GET /wagons.json
  def index
    @wagons = Wagon.all
  end

  # GET /wagons/1
  # GET /wagons/1.json
  def show
  end

  # GET /wagons/new
  def new
    @wagon = Wagon.new
  end

  # GET /wagons/1/edit
  def edit
  end

  # POST /wagons
  # POST /wagons.json
  def create
    @wagon = Wagon.new(wagon_params)

    respond_to do |format|
      if @wagon.save
        format.html { redirect_to wagons_path, notice: 'Wagon was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /wagons/1
  # PATCH/PUT /wagons/1.json
  def update
    respond_to do |format|
      if @wagon.update(wagon_params)
        format.html { redirect_to @wagon, notice: 'Wagon was successfully updated.' }
        format.json { render :show, status: :ok, location: @wagon }
      else
        format.html { render :edit }
        format.json { render json: @wagon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wagons/1
  # DELETE /wagons/1.json
  def destroy
    @wagon.destroy
    respond_to do |format|
      format.html { redirect_to wagons_url, notice: 'Wagon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wagon
      @wagon = Wagon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wagon_params
      params.require(:wagon).permit(:train_id, :comfort, :bottom_seats, :top_seats)
    end
end

app/helpers/wagons_helper.rb
module WagonsHelper
end

app/views/wagons/_form.html.erb
<%= form_for(wagon) do |f| %>
  <% if wagon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wagon.errors.count, "error") %> prohibited this wagon from being saved:</h2>

      <ul>
      <% wagon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="field">
      <%= f.label :train_id %>
      <%= f.select :train_id, Train.all.collect {|t| [ t.number, t.id ] } %>
      <%= f.label :comfort %>
      <%= f.select :comfort, ['Buisness','Econom'] %>
      <%= f.label :bottom_seats %>
      <%= f.number_field :bottom_seats %>
      <%= f.label :top_seats %>
      <%= f.number_field :top_seats %>

    </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/wagons/_wagon.html.erb
<td><%= wagon.train.number %></td>
<td><%= wagon.comfort %></td>
<td><%= wagon.bottom_seats %></td>
<td><%= wagon.top_seats %></td>
<td><%= link_to 'Destroy', wagon, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/wagons/edit.html.erb
<h1>Editing Wagon</h1>

<%= render 'form', wagon: @wagon %>

<%= link_to 'Show', @wagon %> |
<%= link_to 'Back', wagons_path %>

app/views/wagons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wagons</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wagons.each do |wagon| %>
      <tr>
        <%= render wagon %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wagon', new_wagon_path %>

app/views/wagons/new.html.erb
<h1>New Wagon</h1>

<%= render 'form', wagon: @wagon %>

<%= link_to 'Back', wagons_path %>

app/views/wagons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', wagons_path %>